// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA78yXjcj4JCo5Z7QIJrCbTLyhungNnuE',
    appId: '1:42260331164:web:2ddb6bbf57816d6ecf0b59',
    messagingSenderId: '42260331164',
    projectId: 'samia-11824',
    authDomain: 'samia-11824.firebaseapp.com',
    storageBucket: 'samia-11824.appspot.com',
    measurementId: 'G-2DM4DZ4QL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRmXpWQiJXmkRE8scalhMPYMizu2VB9mw',
    appId: '1:42260331164:android:a35e94250dbc3599cf0b59',
    messagingSenderId: '42260331164',
    projectId: 'samia-11824',
    storageBucket: 'samia-11824.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP1MYCWS3hxXb_5AQWptkDKhrgODy2N3U',
    appId: '1:42260331164:ios:e2dbc5320a0ddb53cf0b59',
    messagingSenderId: '42260331164',
    projectId: 'samia-11824',
    storageBucket: 'samia-11824.appspot.com',
    iosBundleId: 'com.example.chitchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP1MYCWS3hxXb_5AQWptkDKhrgODy2N3U',
    appId: '1:42260331164:ios:76924419c5e79fc5cf0b59',
    messagingSenderId: '42260331164',
    projectId: 'samia-11824',
    storageBucket: 'samia-11824.appspot.com',
    iosBundleId: 'com.example.chitchatapp.RunnerTests',
  );
}
